import NavbarSite from 'components/NavbarSite';
import './globals.css';
import SiteFaq from 'components/Landing/SiteFaq';
import SiteFooter from 'components/SiteFooter';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div id="root">
          <NavbarSite />
          {children}
          <SiteFaq />
          <SiteFooter />
        </div>
      </body>
    </html>
  );
}
