import NavbarSite from 'components/NavbarSite';
import SiteFaq from 'components/Landing/SiteFaq';
import SiteFooter from 'components/SiteFooter';

export const metadata = {
  title: 'ArenaZ',
  description: 'Generated by create next app',
};

export default function LoginLayout({ children }) {
  return (
    <section id="Login">
      <NavbarSite />
      {children}
      <SiteFooter />
    </section>
  );
}
